

const SerInfo = [
    { id: '01', name: 'Web Development', desc: 'Catering for all your webdev needs from design to development to deployment.', description: 'Catering for all your webdev needs from design to development to deployment.' },
    { id: '02', name: 'UI/UX Design', desc: ' From wireframing and prototyping to user research and usability testing, we ensure your digital product is both beautiful and functional.', description: 'Great design isn’t just about looks—it’s about creating seamless, intuitive experiences. Our UI/UX design services focus on crafting visually appealing, user-friendly interfaces that enhance engagement and drive conversions. From wireframing and prototyping to user research and usability testing, we ensure your digital product is both beautiful and functional.' },
    { id: '03', name: 'Mobile App Development', desc: ' We specialize in building high-performance, user-friendly apps using React Native for cross-platform development and Android Studio for native Android applications.', description: 'Bring your ideas to life with our expert mobile app development services. We specialize in building high-performance, user-friendly apps using React Native for cross-platform development and Android Studio for native Android applications. Whether you need an iOS, Android, or multi-platform app, we ensure seamless performance, modern UI/UX, and a scalable architecture tailored to your business needs.' },
    { id: '04', name: 'Software Consulting', desc: 'Our software consulting services help you choose the best tech stack, optimize performance, and streamline development processes.', description: 'Empower your business with the right technology solutions. Our software consulting services help you choose the best tech stack, optimize performance, and streamline development processes. Whether you need architecture planning, digital transformation strategies, or system optimization, we provide expert guidance to ensure scalability, security, and efficiency.' },
    { id: '05', name: 'Custom Software Development', desc: ' Whether it’s a desktop application, SaaS platform, or enterprise system, we build scalable, high-performance software that aligns with your goals.', description: 'Every business has unique needs—our custom software development services ensure you get a solution tailored just for you. Whether it’s a desktop application, SaaS platform, or enterprise system, we build scalable, high-performance software that aligns with your goals. From planning to deployment, we focus on functionality, security, and a seamless user experience.' },
    { id: '06', name: 'IT Support & Maintenance ', desc: 'Keep your systems running smoothly with our IT support and maintenance services.', description: "Keep your systems running smoothly with our IT support and maintenance services. We provide regular updates, bug fixes, performance optimization, and security enhancements to ensure your software stays reliable and efficient. Whether it's troubleshooting issues or proactive monitoring, we help you minimize downtime and maximize productivity." }
]


export default SerInfo;